/*  jFUSE-ll provides low level bindings to FUSE in Java
    Copyright (C) <2011>  <Christopher Brumgard>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#define FUSE_USE_VERSION 28

#include "fuse.h"
#include "fuse/fuse_lowlevel.h"
#include "fuse/fuse_lowlevel_compat.h"

#include "config.h"


static inline struct fuse_file_info *get_Fuse_File_Info(
		JNIEnv *env, jobject fileInfo)
{
	/* Declarations */
	jclass class = NULL;
	jfieldID fieldID = NULL;


	/* Gets the field id from the object and class */
	if(((class = (*env)->GetObjectClass(env, fileInfo)) == NULL) ||
	   ((fieldID = (*env)->GetFieldID(env, class,
			   	   	   	   	   	   	   "fuse_file_info_ptr", "J")) == NULL))
	{
		return NULL;
	}

	/* Returns the pointer */
	return (struct fuse_file_info *)((*env)->GetLongField(env, fileInfo, fieldID));
}

/*
 * Class:     fuse_FileInfo
 * Method:    setFlags
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setFlags
  (JNIEnv *env, jobject fileInfo, jlong val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets the flags */
	fi->flags = (int)val;

	/* Return */
	return;
}

/*
 * Class:     fuse_FileInfo
 * Method:    getFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FileInfo_getFlags
  (JNIEnv *env, jobject fileInfo)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Returns the flags */
	return fi->flags;

}

/*
 * Class:     fuse_FileInfo
 * Method:    setWritePage
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setWritePage
  (JNIEnv *env, jobject fileInfo, jboolean val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets the write page */
	fi->writepage = (val == JNI_TRUE) ? 1 : 0;

	/* Returns */
	return;
}

/*
 * Class:     fuse_FileInfo
 * Method:    getWritePage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jFUSE_lowlevel_FileInfo_getWritePage
  (JNIEnv *env, jobject fileInfo)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Gets the write page */
	return (fi->writepage == 1) ? JNI_TRUE : JNI_FALSE;
}

/*
 * Class:     fuse_FileInfo
 * Method:    setDirectIO
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setDirectIO
  (JNIEnv *env, jobject fileInfo, jboolean val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets the direct io */
	fi->direct_io = (val == JNI_TRUE) ? 1 : 0;

	/* Returns */
	return;
}

/*
 * Class:     fuse_FileInfo
 * Method:    getDirectIO
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_jFUSE_lowlevel_FileInfo_getDirectIO
  (JNIEnv *env, jobject fileInfo, jboolean val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Gets the direct io */
	return (fi->direct_io == 1) ? JNI_TRUE : JNI_FALSE;
}

/*
 * Class:     fuse_FileInfo
 * Method:    setKeepCache
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setKeepCache
  (JNIEnv *env, jobject fileInfo, jboolean val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets the keep cache */
	fi->keep_cache = (val == JNI_TRUE) ? 1 : 0;

	/* Returns */
	return;
}

/*
 * Class:     fuse_FileInfo
 * Method:    getKeepCache
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_jFUSE_lowlevel_FileInfo_getKeepCache
  (JNIEnv *env, jobject fileInfo, jboolean val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Gets the keep cache */
	return (fi->keep_cache == 1) ? JNI_TRUE : JNI_FALSE;
}

/*
 * Class:     fuse_FileInfo
 * Method:    setFlush
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setFlush__Z
  (JNIEnv *env, jobject fileInfo, jboolean val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets the flush */
	fi->flush = (val == JNI_TRUE) ? 1 : 0;

	/* Returns */
	return;
}

/*
 * Class:     fuse_FileInfo
 * Method:    setFlush
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jFUSE_lowlevel_FileInfo_setFlush__
  (JNIEnv *env, jobject fileInfo)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* gets the flush */
	return (fi->flush == 1) ? JNI_TRUE : JNI_FALSE;
}

/*
 * Class:     fuse_FileInfo
 * Method:    setNonSeekable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setNonSeekable
  (JNIEnv *env, jobject fileInfo, jboolean val)
{

    /* Seekable is not implemented for fuse less than 2.8 */
#if FUSE_VERSION_MAJOR >= 2 && FUSE_MAJOR_VERSION >= 8

    /* Declarations */
	struct fuse_file_info *fi = NULL;




	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Gets the nonseekable */
	fi->nonseekable = (val == JNI_TRUE) ? 1 : 0;

	/* Returns */
	return;

#else


	/* Throws unsupported operation exception for fuse less than 2.8 */
	jclass class = (*env)->FindClass(env,
								"java.lang.UnsupportedOperationException");

	if(class == NULL)
	{
		return;
	}

	(*env)->ThrowNew(env, class, "Seekable not implmented for fuse < 2.8");

	return;

#endif
}

/*
 * Class:     fuse_FileInfo
 * Method:    getNonSeekable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jFUSE_lowlevel_FileInfo_getNonSeekable
  (JNIEnv *env, jobject fileInfo)
{
/* Seekable is not implemented for fuse less than 2.8 */
#if FUSE_VERSION_MAJOR >= 2 && FUSE_MAJOR_VERSION >= 8

    /* Declarations */
	struct fuse_file_info *fi = NULL;



	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Returns the nonseekable */
	return (fi->nonseekable == 1) ? JNI_TRUE : JNI_FALSE;
#else


	/* Throws unsupported operation exception for fuse less than 2.8 */
	jclass class = (*env)->FindClass(env,
								"java.lang.UnsupportedOperationException");

	if(class == NULL)
	{
		return -1;
	}

	(*env)->ThrowNew(env, class, "Seekable not implmented for fuse < 2.8");

	return JNI_FALSE;

#endif
}

/*
 * Class:     fuse_FileInfo
 * Method:    setFh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setFh
  (JNIEnv *env, jobject fileInfo, jlong fh)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets fh */
	fi->fh = (uint64_t)fh;

	/* Returns */
	return;
}

/*
 * Class:     fuse_FileInfo
 * Method:    getFh
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FileInfo_getFh
  (JNIEnv *env, jobject fileInfo)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Returns the fh */
	return (jlong)(fi->fh);
}

/*
 * Class:     fuse_FileInfo
 * Method:    setLockOwner
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FileInfo_setLockOwner
  (JNIEnv *env, jobject fileInfo, jlong val)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return;
	}

	/* Sets fh */
	fi->lock_owner = (jlong)val;

	/* Returns */
	return;
}


/*
 * Class:     jFUSE_lowlevel_FileInfo
 * Method:    getLockOwner
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FileInfo_getLockOwner
  (JNIEnv *env, jobject fileInfo)
{
	/* Declarations */
	struct fuse_file_info *fi = NULL;


	/* Gets the pointer to the internal FileInfo struct or throws an exception*/
	fi = get_Fuse_File_Info(env, fileInfo);

	if(fi == NULL)
	{
		return -1;
	}

	/* Returns the lock owner */
	return (jlong)(fi->lock_owner);
}


