/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_FuseBufferCopyFlags */

#ifndef _Included_jFUSE_lowlevel_FuseBufferCopyFlags
#define _Included_jFUSE_lowlevel_FuseBufferCopyFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef jFUSE_lowlevel_FuseBufferCopyFlags_VOID
#define jFUSE_lowlevel_FuseBufferCopyFlags_VOID 0L
/*
 * Class:     jFUSE_lowlevel_FuseBufferCopyFlags
 * Method:    _getFUSE_BUF_NO_SPLICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_FuseBufferCopyFlags__1getFUSE_1BUF_1NO_1SPLICE
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_FuseBufferCopyFlags
 * Method:    _getFUSE_BUF_FORCE_SPLICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_FuseBufferCopyFlags__1getFUSE_1BUF_1FORCE_1SPLICE
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_FuseBufferCopyFlags
 * Method:    _getFUSE_BUF_SPLICE_MOVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_FuseBufferCopyFlags__1getFUSE_1BUF_1SPLICE_1MOVE
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_FuseBufferCopyFlags
 * Method:    _getFUSE_BUF_SPLICE_NONBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_FuseBufferCopyFlags__1getFUSE_1BUF_1SPLICE_1NONBLOCK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
