/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_Splice */

#ifndef _Included_jFUSE_lowlevel_Splice
#define _Included_jFUSE_lowlevel_Splice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    _SPLICE_F_MOVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_Splice__1SPLICE_1F_1MOVE
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    _SPLICE_F_NONBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_Splice__1SPLICE_1F_1NONBLOCK
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    _SPLICE_F_MORE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_Splice__1SPLICE_1F_1MORE
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    _SPLICE_F_GIFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_Splice__1SPLICE_1F_1GIFT
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    splice
 * Signature: (Ljava/io/FileDescriptor;JLjava/io/FileDescriptor;JJI)J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_Splice_splice
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong, jint);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    tee
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;JI)J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_Splice_tee
  (JNIEnv *, jclass, jobject, jobject, jlong, jint);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    getFileDescriptorFromSocket
 * Signature: (Ljava/net/Socket;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_jFUSE_lowlevel_Splice_getFileDescriptorFromSocket
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    getFileDescriptorFromSocketChannel
 * Signature: (Ljava/nio/channels/SocketChannel;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_jFUSE_lowlevel_Splice_getFileDescriptorFromSocketChannel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jFUSE_lowlevel_Splice
 * Method:    createPipeFileDescriptor
 * Signature: ()LjFUSE/lowlevel/Splice/Pipe;
 */
JNIEXPORT jobject JNICALL Java_jFUSE_lowlevel_Splice_createPipeFileDescriptor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
