/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_FLock_Whence */

#ifndef _Included_jFUSE_lowlevel_FLock_Whence
#define _Included_jFUSE_lowlevel_FLock_Whence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jFUSE_lowlevel_FLock_Whence
 * Method:    assignValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jFUSE_lowlevel_FLock_00024Whence_assignValue
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
