/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_FuseArgs */

#ifndef _Included_jFUSE_lowlevel_FuseArgs
#define _Included_jFUSE_lowlevel_FuseArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jFUSE_lowlevel_FuseArgs
 * Method:    _initializeFuseArgs
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseArgs__1initializeFuseArgs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     jFUSE_lowlevel_FuseArgs
 * Method:    _freeFuseArgs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseArgs__1freeFuseArgs
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseArgs
 * Method:    addArg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseArgs_addArg
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
