
/*  jFUSE-ll provides low level bindings to FUSE in Java
    Copyright (C) <2011>  <Christopher Brumgard>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_FuseErrno */

#ifndef _Included_jFUSE_lowlevel_FuseErrno
#define _Included_jFUSE_lowlevel_FuseErrno
#ifdef __cplusplus
extern "C" {
#endif
#undef jFUSE_lowlevel_FuseErrno_EPERM
#define jFUSE_lowlevel_FuseErrno_EPERM 1L
#undef jFUSE_lowlevel_FuseErrno_ENOENT
#define jFUSE_lowlevel_FuseErrno_ENOENT 2L
#undef jFUSE_lowlevel_FuseErrno_ESRCH
#define jFUSE_lowlevel_FuseErrno_ESRCH 3L
#undef jFUSE_lowlevel_FuseErrno_EINTR
#define jFUSE_lowlevel_FuseErrno_EINTR 4L
#undef jFUSE_lowlevel_FuseErrno_EIO
#define jFUSE_lowlevel_FuseErrno_EIO 5L
#undef jFUSE_lowlevel_FuseErrno_ENXIO
#define jFUSE_lowlevel_FuseErrno_ENXIO 6L
#undef jFUSE_lowlevel_FuseErrno_E2BIG
#define jFUSE_lowlevel_FuseErrno_E2BIG 7L
#undef jFUSE_lowlevel_FuseErrno_ENOEXEC
#define jFUSE_lowlevel_FuseErrno_ENOEXEC 8L
#undef jFUSE_lowlevel_FuseErrno_EBADF
#define jFUSE_lowlevel_FuseErrno_EBADF 9L
#undef jFUSE_lowlevel_FuseErrno_ECHILD
#define jFUSE_lowlevel_FuseErrno_ECHILD 10L
#undef jFUSE_lowlevel_FuseErrno_EAGAIN
#define jFUSE_lowlevel_FuseErrno_EAGAIN 11L
#undef jFUSE_lowlevel_FuseErrno_ENOMEM
#define jFUSE_lowlevel_FuseErrno_ENOMEM 12L
#undef jFUSE_lowlevel_FuseErrno_EACCES
#define jFUSE_lowlevel_FuseErrno_EACCES 13L
#undef jFUSE_lowlevel_FuseErrno_EFAULT
#define jFUSE_lowlevel_FuseErrno_EFAULT 14L
#undef jFUSE_lowlevel_FuseErrno_ENOTBLK
#define jFUSE_lowlevel_FuseErrno_ENOTBLK 15L
#undef jFUSE_lowlevel_FuseErrno_EBUSY
#define jFUSE_lowlevel_FuseErrno_EBUSY 16L
#undef jFUSE_lowlevel_FuseErrno_EEXIST
#define jFUSE_lowlevel_FuseErrno_EEXIST 17L
#undef jFUSE_lowlevel_FuseErrno_EXDEV
#define jFUSE_lowlevel_FuseErrno_EXDEV 18L
#undef jFUSE_lowlevel_FuseErrno_ENODEV
#define jFUSE_lowlevel_FuseErrno_ENODEV 19L
#undef jFUSE_lowlevel_FuseErrno_ENOTDIR
#define jFUSE_lowlevel_FuseErrno_ENOTDIR 20L
#undef jFUSE_lowlevel_FuseErrno_EISDIR
#define jFUSE_lowlevel_FuseErrno_EISDIR 21L
#undef jFUSE_lowlevel_FuseErrno_EINVAL
#define jFUSE_lowlevel_FuseErrno_EINVAL 22L
#undef jFUSE_lowlevel_FuseErrno_ENFILE
#define jFUSE_lowlevel_FuseErrno_ENFILE 23L
#undef jFUSE_lowlevel_FuseErrno_EMFILE
#define jFUSE_lowlevel_FuseErrno_EMFILE 24L
#undef jFUSE_lowlevel_FuseErrno_ENOTTY
#define jFUSE_lowlevel_FuseErrno_ENOTTY 25L
#undef jFUSE_lowlevel_FuseErrno_ETXTBSY
#define jFUSE_lowlevel_FuseErrno_ETXTBSY 26L
#undef jFUSE_lowlevel_FuseErrno_EFBIG
#define jFUSE_lowlevel_FuseErrno_EFBIG 27L
#undef jFUSE_lowlevel_FuseErrno_ENOSPC
#define jFUSE_lowlevel_FuseErrno_ENOSPC 28L
#undef jFUSE_lowlevel_FuseErrno_ESPIPE
#define jFUSE_lowlevel_FuseErrno_ESPIPE 29L
#undef jFUSE_lowlevel_FuseErrno_EROFS
#define jFUSE_lowlevel_FuseErrno_EROFS 30L
#undef jFUSE_lowlevel_FuseErrno_EMLINK
#define jFUSE_lowlevel_FuseErrno_EMLINK 31L
#undef jFUSE_lowlevel_FuseErrno_EPIPE
#define jFUSE_lowlevel_FuseErrno_EPIPE 32L
#undef jFUSE_lowlevel_FuseErrno_EDOM
#define jFUSE_lowlevel_FuseErrno_EDOM 33L
#undef jFUSE_lowlevel_FuseErrno_ERANGE
#define jFUSE_lowlevel_FuseErrno_ERANGE 34L
#ifdef __cplusplus
}
#endif
#endif
