/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_FLock */

#ifndef _Included_jFUSE_lowlevel_FLock
#define _Included_jFUSE_lowlevel_FLock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    _allocate_flock
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FLock__1allocate_1flock
  (JNIEnv *, jclass);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    _free_flock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FLock__1free_1flock
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    getType
 * Signature: ()LjFUSE/lowlevel/FLock/Type;
 */
JNIEXPORT jobject JNICALL Java_jFUSE_lowlevel_FLock_getType
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    setType
 * Signature: (LjFUSE/lowlevel/FLock/Type;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FLock_setType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    getWhence
 * Signature: ()LjFUSE/lowlevel/FLock/Whence;
 */
JNIEXPORT jobject JNICALL Java_jFUSE_lowlevel_FLock_getWhence
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    setWhence
 * Signature: (LjFUSE/lowlevel/FLock/Whence;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FLock_setWhence
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    getStart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FLock_getStart
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    setStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FLock_setStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    getLen
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FLock_getLen
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    setLen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FLock_setLen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    getPid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_FLock_getPid
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FLock
 * Method:    setPid
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FLock_setPid
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
