/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_Splice_Pipe */

#ifndef _Included_jFUSE_lowlevel_Splice_Pipe
#define _Included_jFUSE_lowlevel_Splice_Pipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jFUSE_lowlevel_Splice_Pipe
 * Method:    _setSize
 * Signature: (Ljava/io/FileDescriptor;J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_Splice_00024Pipe__1setSize
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     jFUSE_lowlevel_Splice_Pipe
 * Method:    _getSize
 * Signature: (Ljava/io/FileDescriptor;)J
 */
JNIEXPORT jlong JNICALL Java_jFUSE_lowlevel_Splice_00024Pipe__1getSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_Splice_Pipe
 * Method:    _close
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_Splice_00024Pipe__1close
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
