/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jFUSE_lowlevel_FuseRequest */

#ifndef _Included_jFUSE_lowlevel_FuseRequest
#define _Included_jFUSE_lowlevel_FuseRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_none
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1none
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_err
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1err
  (JNIEnv *, jobject, jint);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_entry
 * Signature: (LjFUSE/lowlevel/FuseEntryParam;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1entry
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_attr
 * Signature: (LjFUSE/lowlevel/FuseStat;D)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1attr
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_open
 * Signature: (LjFUSE/lowlevel/FileInfo;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1open
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_write
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1write
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_buf
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1buf
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_mbuf
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1mbuf
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_iov
 * Signature: ([Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1iov
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_create
 * Signature: (LjFUSE/lowlevel/FuseEntryParam;LjFUSE/lowlevel/FileInfo;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1create
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_lock
 * Signature: (LjFUSE/lowlevel/FLock;)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1lock
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_xattr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1xattr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    getCTX
 * Signature: ()LjFUSE/lowlevel/FuseCTX;
 */
JNIEXPORT jobject JNICALL Java_jFUSE_lowlevel_FuseRequest_getCTX
  (JNIEnv *, jobject);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    add_direntry
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;LjFUSE/lowlevel/FuseStat;J)Z
 */
JNIEXPORT jboolean JNICALL Java_jFUSE_lowlevel_FuseRequest_add_1direntry
  (JNIEnv *, jobject, jobject, jstring, jobject, jlong);

/*
 * Class:     jFUSE_lowlevel_FuseRequest
 * Method:    reply_data
 * Signature: (Ljava/util/List;I)V
 */
JNIEXPORT void JNICALL Java_jFUSE_lowlevel_FuseRequest_reply_1data
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
